In [ ]:
def make_noisy_test_data(p_true,Npnt,msmnt_err):
    """
    
    Make noisy test data.

    Parameters
    ----------
    p_true      : true fitted parameters values (n x 1), must be 2D array
    Npnt        : number of data points (m = Npnt)
    msmnt_err   : amount of noise added to model data

    Returns
    -------
    x           : x-values of test data (m x 1), must be 2D array
    y           : y-values of test data (m x 1), must be 2D array

    """
    
    x = np.array(range(Npnt)).T
    y_true = lm_func(x,p_true)
    
    # add random measurement errors
    rng = np.random.default_rng()
    y = y_true + msmnt_err*rng.random((Npnt)) 
    
    return x,y

In [2]:
import numpy as np
import seaborn as sns
import matplotlib.pylab as pl
import matplotlib.pyplot as plt

In [3]:
p_true = np.array([[6,20,1,5]]).T

In [4]:
p_true

array([[ 6],
       [20],
       [ 1],
       [ 5]])

In [5]:
eps = 2**(-52)

In [7]:
eps

2.220446049250313e-16

In [8]:
p_old  = np.zeros((5,1))

In [9]:
p_old

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [10]:
J      = np.zeros((10,5))

In [11]:
J

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])