# Searching in matrix

In [24]:
import numpy as np
a = np.array([[1,2,4,6],[8,9,12,16],[20,21,23,24]])
print(a)

[[ 1  2  4  6]
 [ 8  9 12 16]
 [20 21 23 24]]


In [25]:
len(a[1])

4

In [26]:
def binary(r , b):
    low = 0
    high = len(r)
    mid = int((low+high)/2)
    while low < high:
        if b == r[mid]:
            return 'yes'
        elif b < r[mid]:
            high = mid - 1
            mid = int((low + high)/2)
        else:
            low = mid + 1 
            mid = int((high + low)/2)
    return 'no'

In [27]:
#r = [8,9,12,16]
r = a[1]
s = binary(r, 20)
print(s)

no


In [28]:

c = 9
for i in range(a.shape[0]):
    if c < a[i][a.shape[1]-1]:
        r = a[i]
        s = binary(r, c)
        print(s)
        break
        

no


space complexity is 1

do binary search on column and row.

time complexity is lgm + lgn

# Merging 2 list

In [8]:
l1 = [1,2,2,3,10]
l2 = [3,4,6,20]

z = []
r = 0
i = 0
while i < len(l1) and r < len(l2):
    if l1[i] < l2[r]:
        z.append(l1[i])
        i = i + 1
    elif l1[i] == l2[r]:
        z.append(l1[i])
        i =  i + 1
    else :
        z.append(l2[r])
        r = r + 1        
    

In [9]:
z

[1, 2, 2, 3, 3, 4, 6, 10]

time compledxity is m + n
space coplexity is o of 1

# sort the list

In [6]:
l = [5,3,7,6,10,2]
a = 0
for i in range(6):
    temp = l[i]
    for j in range(i+1,6):
        if l[i] > l[j]:
           temp = l[j]
    l[i] = a 
    a = 0

In [7]:
l

[2, 2, 2, 2, 2, 0]